### ISSUE TITLE
 Adafruit_SH1106G not working on SPI

### ISSUE THREAD

**Issue by gps79** [adafruit/Adafruit_SH110x#10]
- Arduino board:  **NodeMCU v3**
- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.15**

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**
1. Build and run example https://github.com/adafruit/Adafruit_SH110x/blob/master/examples/OLED_QTPY_SH1106/SH1106_128x64_SPi_QTPY/SH1106_128x64_SPi_QTPY.ino

**Expected result:**
Software runs without errors.

**Actual result:**
Software crashes.

**Root cause:**
- file: Adafruit_SH110X.cpp
- method: void Adafruit_SH110X::display(void)
- line: uint16_t maxbuff = i2c_dev->maxBufferSize() - 1;
- cause: i2c_dev is null for SPI connection

**Comment by ladyada** [comment]
are you using adafruit hardware? if so please post a photo!

**Comment by gps79** [comment]
I don't use adafruit hardware.
I just pointed an error (i2c_dev is a null pointer and causes crash).
The fix for that is to move line:
uint16_t maxbuff = i2c_dev->maxBufferSize() - 1;
below line:
    if (i2c_dev) { // I2C

so it's executed only when  i2c_dev structure is initialized.
Then the SW doesn't crash.

**Comment by caternuson** [comment]
What code are you running? Is it calling `begin()` on the display instance?

**EDIT** - oh, this is for **SPI** usage. OK, seeing it now. For the SPI case, `i2c_dev` never gets init'd:
https://github.com/adafruit/Adafruit-GFX-Library/blob/4a33fcd467e373d1eedd3aef6f5f9be36f5c276b/Adafruit_GrayOLED.cpp#L242-L252
so the call to `display()` will try to access a null pointer here:
https://github.com/adafruit/Adafruit_SH110x/blob/2f7d9fbdc6596d449d303bd7d8b44399012a27de/Adafruit_SH110X.cpp#L170

**Comment by caternuson** [comment]
@gps79 If you can, please test the changes in PR #11.

**Comment by gps79** [comment]
It's working fine with your fix. No more crashes.
Thank you.
