### ISSUE TITLE
More then one Screen

### ISSUE THREAD

**Issue by phtoth** [adafruit/Adafruit_SH110x#12]
Hello, how are you?

I had tried using the latest version of this lib with two screens, but with no success. Have you ever tried?

Best Regards

**Comment by ladyada** [comment]
we haven't - it should work just make sure you have enough RAM and there is no address conflict. where exactly did you purchase the screen (URL)

**Comment by phtoth** [comment]
Aliexpress. I changed the resistor of one screen, now I have one in 0x3c address and the other on 0x3d. in a test done separately, both screen works normally. but when I try with both, one do not turns on and the other not work properly.

here's my code:  

`/*********************************************************************
  This is an example for our Monochrome OLEDs based on SH110X drivers

  This example is for a 128x64 size display using I2C to communicate
  3 pins are required to interface (2 I2C and one reset)

  Adafruit invests time and resources providing this open source code,
  please support Adafruit and open-source hardware by purchasing
  products from Adafruit!

  Written by Limor Fried/Ladyada  for Adafruit Industries.
  BSD license, check license.txt for more information
  All text above, and the splash screen must be included in any redistribution

  i2c SH1106 modified by Rupert Hirst  12/09/21
*********************************************************************/



#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SH110X.h>

/* Uncomment the initialize the I2C address , uncomment only one, If you get a totally blank screen try the other*/
#define i2c_Address 0x3c //initialize with the I2C addr 0x3C Typically eBay OLED's
#define i2c_Address_2 0x3d //initialize with the I2C addr 0x3D Typically Adafruit OLED's

#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 64 // OLED display height, in pixels
#define OLED_RESET -1   //   QT-PY / XIAO
Adafruit_SH1106G display = Adafruit_SH1106G(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

Adafruit_SH1106G display2 = Adafruit_SH1106G(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

#define NUMFLAKES 10
#define XPOS 0
#define YPOS 1
#define DELTAY 2




void setup()   {

  Serial.begin(9600);

  // Show image buffer on the display hardware.
  // Since the buffer is intialized with an Adafruit splashscreen
  // internally, this will display the splashscreen.

  delay(250); // wait for the OLED to power up

  
  display.begin(i2c_Address_2, true); // Address 0x3C default

  display2.begin(i2c_Address, true);
    
 //display.setContrast (0); // dim display
 
  display.display();
  delay(2000);

  // Clear the buffer.
  display.clearDisplay();


  // text display tests
  display.setTextSize(1);
  display.setTextColor(SH110X_WHITE);
  display.setCursor(0, 0);
  display.println("Failure is always an option");
  display.setTextColor(SH110X_BLACK, SH110X_WHITE); // 'inverted' text
  display.println(3.141592);
  display.setTextSize(2);
  display.setTextColor(SH110X_WHITE);
  display.print("0x"); display.println(0xDEADBEEF, HEX);
  display.display();
  delay(2000);
  display.clearDisplay();


}


void loop() {

}


`

**Comment by phtoth** [comment]
![IMG_2932](https://user-images.githubusercontent.com/36824478/161291144-2ace3ffa-eee2-465e-92b9-4cca98db891d.jpeg)

the connections are made correctly, I swear ;-)

**Comment by ladyada** [comment]
you dont have enough ram so it will never work.
