### ISSUE TITLE
Marking SH1106G and marking  SH1107

### ISSUE THREAD

**Issue by zz912** [adafruit/Adafruit_SH110x#18]
Hello,

I wanted to ask why the SH1106 chip contains the letter G and the SH1107 chip does not?
In the datasheet, the designation G is gold. Did they forget to add the G for SH1107, or does it mean something else entirely?

Zdenek

**Comment by caternuson** [comment]
These issues are for reporting software related problems with the code hosted in this repo. Closing since not related to repo code.
