### ISSUE TITLE
Issue when using SH1107 with an MPU-6050 (Both Adafruit libraries)

### ISSUE THREAD

**Issue by AndyBadger** [adafruit/Adafruit_SH110x#9]
When using both the SH1107 and the MPU_6050 the micro goes into reset during the begin command for the display.  I have looked at the I2C bus on a scope and do not see the 0x3c address going out during the display init.

**Comment by caternuson** [comment]
Please post in the forums with photos of your setup and an example sketch that demonstrates the issue:
https://forums.adafruit.com/
